// Generated by CoffeeScript 1.6.2
(function() {
  var defaultText, maxNum;

  $("#name-input").attr("disabled", true).addClass("disable");

  defaultText = "Search";

  $("input").on("focus", function() {
    $(this).addClass("highlight");
    if ($(this).val() === defaultText) {
      return $(this).val("").removeClass("default");
    }
  }).on("blur", function() {
    $(this).removeClass("highlight");
    if ($(this).val() === "") {
      return $(this).val(defaultText).addClass("default");
    }
  });

  $("input:first").focus();

  maxNum = 140;

  $("#status").on("keydown", function(event) {
    var charRemain, inputText, numChar;

    inputText = $(this).val();
    numChar = inputText.length;
    charRemain = maxNum - numChar;
    if (numChar <= maxNum) {
      $("#counter strong").text("剩余");
      $("#counter span").text(charRemain);
    }
    if (numChar > maxNum) {
      $("#counter strong").text("超过");
      return $("#counter span").text(charRemain / -1);
    }
  }).on("keyup", function(event) {
    var charRemain, inputText, numChar;

    inputText = $(this).val();
    numChar = inputText.length;
    charRemain = maxNum - numChar;
    if (numChar <= maxNum) {
      $("#counter strong").text("剩余");
      $("#counter span").text(charRemain);
    }
    if (numChar > maxNum) {
      $("#counter strong").text("超过");
      return $("#counter span").text(charRemain / -1);
    }
  });

}).call(this);
