// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    paths: {
      'jquery': 'vendor/jquery/jquery',
      'qTip': 'vendor/qtip2/dist/jquery.qtip'
    },
    shim: {
      'qTip': ['jquery']
    }
  });

  require(['jquery'], function($) {
    return $('select').on('change', function() {
      return $('#show').text($(this).val());
    });
  });

  require(['jquery'], function($) {
    $("#email-form").prepend('<div class="email-error"></div>');
    return $('#email-submit').on('click', function() {
      var email, emailReg;
      emailReg = /^(\w)+(\.\w+)*@(\w)+((\.\w{2,3}){1,3})$/;
      email = $("#email").val();
      if (email === '') {
        $(".email-error").text('You forgot to enter an email address.');
      } else if (!emailReg.test(email)) {
        $(".email-error").text('Your email: "' + email + '" is wrong! Please enter a valid email addreess.');
      } else {
        $('#email-form').html('<div class="sucess">Thank you, you have been subscribed.</div>');
      }
      return false;
    });
  });

}).call(this);
