// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    var $;
    $ = require('jquery');
    $().ready($('#content').load('ajax-content.html'));
    $().ready($('#error').load('ajax-error.html', function(responseText, textStatus, XMLHttpRequest) {
      if (XMLHttpRequest.status === 404 || XMLHttpRequest === 500) {
        return $("#error").html('There has been an error, please try again later.');
      } else {

      }
    }));
    $(function() {
      return $.ajax({
        type: 'POST',
        url: 'ajax-content.html'
      }).fail($('#error').html('#error-2 has been an error, please try again later.'));
    });
    return $('#loading').html('<img src="images/loading.gif" alt="loading...">');
  });

}).call(this);
