// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    baseUrl: 'scripts',
    paths: {
      'jquery': 'vendor/jquery/jquery',
      'qTip': 'vendor/qTip/jquery.qtip',
      'qTip2': 'vendor/qtip2/dist/jquery.qtip',
      'jquery-migrate': 'vendor/jquery-migrate/jquery-migrate',
      'validate': 'vendor/jquery-validation/jquery.validate'
    },
    shim: {
      'qTip': ['jquery', 'jquery-migrate'],
      'qTip2': ['jquery', 'jquery-migrate'],
      'validate': ['jquery']
    }
  });

}).call(this);
