// Generated by CoffeeScript 1.6.3
(function() {
  require(['jquery', 'qTip'], function($) {
    return $('#email-input').qtip({
      style: {
        coloer: 'black',
        name: 'black'
      }
    });
  });

}).call(this);
