// Generated by CoffeeScript 1.6.3
(function() {
  require(['jquery', 'qTip'], function($) {
    return $('#email-input').qtip({
      show: {
        when: {
          event: 'focus'
        }
      },
      hide: {
        when: {
          event: 'blur'
        }
      },
      position: {
        corner: {
          target: 'bottomRight'
        }
      },
      style: {
        color: 'black',
        tip: true,
        name: 'blue',
        border: {
          radius: 5
        }
      }
    });
  });

}).call(this);
