// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    var $, color;
    $ = require('jquery');
    color = '';
    $('tbody tr').on('mouseover', function() {
      color = $(this).css('background-color');
      return $(this).css({
        'background': '#ECFBD4'
      });
    }).on('mouseout', function() {
      return $(this).css({
        'background': color
      });
    });
    $('tbody tr:even').addClass('even');
    return $('tbody tr:odd').addClass('odd');
  });

}).call(this);
