// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    var $, i, numShows, numTickets, numTotal, _results;
    $ = require('jquery');
    numShows = 10;
    numTickets = 100;
    i = 0;
    _results = [];
    while (i < numTickets) {
      numTotal = i + 1;
      $('.container').append("<p>There are " + numTotal + " tickets available</p>");
      _results.push(i++);
    }
    return _results;
  });

}).call(this);
